import { eq } from 'drizzle-orm'
import type { Pool } from 'pg'
import { metadataConfigTable, tagCategories } from '../schema'

export const productionCuisines = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andalusian',
  'Angolan',
  'Antiguan',
  'Argentinian',
  'Armenian',
  'Ashkenazi',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Basque',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bengali',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burmese',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Caribbean',
  'Catalan',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Creole',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Dominican',
  'Dutch',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'English',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Filipino',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Guatemalan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Hawaiian',
  'Honduran',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Javanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Korean',
  'Kurdish',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latin American',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Lithuanian',
  'Louisiana',
  'Luxembourgish',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Manx',
  'Maori',
  'Mauritanian',
  'Mauritian',
  'Mediterranean',
  'Mexican',
  'Moldovan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Navajo',
  'Nepalese',
  'New Zealand',
  'Nicaraguan',
  'Nigerian',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Ottoman',
  'Pakistani',
  'Palestinian',
  'Panamanian',
  'Paraguayan',
  'Persian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Puerto Rican',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Samoan',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sicilian',
  'Sierra Leonean',
  'Singaporean',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'South African',
  'South American',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tamil',
  'Tanzanian',
  'Thai',
  'Tibetan',
  'Togolese',
  'Tongan',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
  'Acadian',
  'Appalachian',
  'Californian',
  'Cajun',
  'Chesapeake',
  'New England',
  'New Mexican',
  'Southern American',
  'Tex-Mex',
  'Soul Food',
  'Cantonese',
  'Hakka',
  'Hainanese',
  'Hunanese',
  'Sichuan',
  'Shandong',
  'Shanghai',
  'Fujian',
  'Yunnanese',
  'Xinjiang',
  'Jeju',
  'Goan',
  'Gujarati',
  'Hyderabadi',
  'Kashmiri',
  'Kerala',
  'Maharashtrian',
  'Mughlai',
  'Punjabi',
  'Rajasthani',
  'Sindhi',
  'Chettinad',
  'Andhra',
  'Telugu',
  'Awadhi',
  'Lucknowi',
  'Balinese',
  'Sundanese',
  'Minangkabau',
  'Peranakan',
  'Nyonya',
  'Okinawan',
  'Northern Vietnamese',
  'Southern Vietnamese',
  'Isan',
  'Lao',
  'Ilocano',
  'Galician',
  'Valencian',
  'Asturian',
  'Canarian',
  'Madeiran',
  'Azorean',
  'Neapolitan',
  'Tuscan',
  'Roman',
  'Ligurian',
  'Venetian',
  'Emilian',
  'Piedmontese',
  'Sardinian',
  'Calabrian',
  'Apulian',
  'Provençal',
  'Occitan',
  'Alsatian',
  'Breton',
  'Norman',
  'Burgundian',
  'Savoyard',
  'Corsican',
  'Flemish',
  'Walloon',
  'Frisian',
  'Bavarian',
  'Swabian',
  'Saxon',
  'Rhenish',
  'Viennese',
  'Silesian',
  'Moravian',
  'Dalmatian',
  'Central Asian',
  'Arabian',
  'Levantine',
  'Middle Eastern',
  'Gulf',
  'North African',
  'West African',
  'East African',
  'Cape Malay',
  'Yucatecan',
  'Oaxacan',
  'Pueblan',
  'Veracruz',
  'Jalisco',
  'Mayan',
  'Central American',
  'Salvadoran',
  'Amazonian',
  'Andean',
]

export const productionTagCategories = [
  {
    id: 'course',
    name: 'Course',
    color: 'blue',
    exclusive: false,
    minTags: 1,
    maxTags: 5,
    tags: ['appetizer', 'main', 'side', 'dessert', 'breakfast'],
  },
  {
    id: 'weather',
    name: 'Weather',
    color: 'amber',
    exclusive: true,
    minTags: 1,
    maxTags: 1,
    tags: ['cold', 'warm', 'any'],
  },
  {
    id: 'occasion',
    name: 'Occasion',
    color: 'purple',
    exclusive: true,
    minTags: 1,
    maxTags: 1,
    tags: ['Everyday', 'Weekend', 'Festive'],
  },
  {
    id: 'cuisine',
    name: 'Cuisine',
    color: 'emerald',
    exclusive: false,
    minTags: 1,
    maxTags: 5,
    tags: productionCuisines,
  },
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function seedProduction(db: any, _pool: Pool): Promise<void> {
  // 1. Seed global metadata configuration if missing
  const existingConfig = await db
    .select()
    .from(metadataConfigTable)
    .where(eq(metadataConfigTable.id, 'global'))

  if (existingConfig.length === 0) {
    console.log('[Seed:Production] Seeding global metadata configuration...')
    await db.insert(metadataConfigTable).values({
      id: 'global',
      mandatoryFields: {
        title: true,
        ingredients: true,
        instructions: true,
        image_url: false,
        description: false,
        yield_amount: false,
        prep_time_minutes: false,
        cook_time_minutes: false,
        source_url: false,
      },
      mandatoryCategories: ['course', 'weather', 'occasion', 'cuisine'],
      timeTrackingMode: 'prep_and_cook',
    })
  }

  // 2. Seed production tag categories if not present
  for (const cat of productionTagCategories) {
    const existing = await db
      .select()
      .from(tagCategories)
      .where(eq(tagCategories.id, cat.id))

    if (existing.length === 0) {
      await db.insert(tagCategories).values(cat)
    }
  }
}
