import { eq } from 'drizzle-orm'
import type { Pool } from 'pg'
import { metadataConfigTable, tagCategories, templates, templateVersions } from '../schema'

export const productionCuisines = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andalusian',
  'Angolan',
  'Antiguan',
  'Argentinian',
  'Armenian',
  'Ashkenazi',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Basque',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bengali',
  'Bhutanese',
  'Bolivian',
  'Bosnian',
  'Botswanan',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burmese',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Caribbean',
  'Catalan',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Creole',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Dominican',
  'Dutch',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'English',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Filipino',
  'Finnish',
  'French',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Guatemalan',
  'Guinean',
  'Guyanese',
  'Haitian',
  'Hawaiian',
  'Honduran',
  'Hungarian',
  'Icelandic',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Javanese',
  'Jordanian',
  'Kazakh',
  'Kenyan',
  'Korean',
  'Kurdish',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latin American',
  'Latvian',
  'Lebanese',
  'Liberian',
  'Libyan',
  'Lithuanian',
  'Louisiana',
  'Luxembourgish',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Manx',
  'Maori',
  'Mauritanian',
  'Mauritian',
  'Mediterranean',
  'Mexican',
  'Moldovan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Navajo',
  'Nepalese',
  'New Zealand',
  'Nicaraguan',
  'Nigerian',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Ottoman',
  'Pakistani',
  'Palestinian',
  'Panamanian',
  'Paraguayan',
  'Persian',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Puerto Rican',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Samoan',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sicilian',
  'Sierra Leonean',
  'Singaporean',
  'Sinhalese',
  'Slovak',
  'Slovenian',
  'Somali',
  'South African',
  'South American',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tamil',
  'Tanzanian',
  'Thai',
  'Tibetan',
  'Togolese',
  'Tongan',
  'Trinidadian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
  'Acadian',
  'Appalachian',
  'Californian',
  'Cajun',
  'Chesapeake',
  'New England',
  'New Mexican',
  'Southern American',
  'Tex-Mex',
  'Soul Food',
  'Cantonese',
  'Hakka',
  'Hainanese',
  'Hunanese',
  'Sichuan',
  'Shandong',
  'Shanghai',
  'Fujian',
  'Yunnanese',
  'Xinjiang',
  'Jeju',
  'Goan',
  'Gujarati',
  'Hyderabadi',
  'Kashmiri',
  'Kerala',
  'Maharashtrian',
  'Mughlai',
  'Punjabi',
  'Rajasthani',
  'Sindhi',
  'Chettinad',
  'Andhra',
  'Telugu',
  'Awadhi',
  'Lucknowi',
  'Balinese',
  'Sundanese',
  'Minangkabau',
  'Peranakan',
  'Nyonya',
  'Okinawan',
  'Northern Vietnamese',
  'Southern Vietnamese',
  'Isan',
  'Lao',
  'Ilocano',
  'Galician',
  'Valencian',
  'Asturian',
  'Canarian',
  'Madeiran',
  'Azorean',
  'Neapolitan',
  'Tuscan',
  'Roman',
  'Ligurian',
  'Venetian',
  'Emilian',
  'Piedmontese',
  'Sardinian',
  'Calabrian',
  'Apulian',
  'Provençal',
  'Occitan',
  'Alsatian',
  'Breton',
  'Norman',
  'Burgundian',
  'Savoyard',
  'Corsican',
  'Flemish',
  'Walloon',
  'Frisian',
  'Bavarian',
  'Swabian',
  'Saxon',
  'Rhenish',
  'Viennese',
  'Silesian',
  'Moravian',
  'Dalmatian',
  'Central Asian',
  'Arabian',
  'Levantine',
  'Middle Eastern',
  'Gulf',
  'North African',
  'West African',
  'East African',
  'Cape Malay',
  'Yucatecan',
  'Oaxacan',
  'Pueblan',
  'Veracruz',
  'Jalisco',
  'Mayan',
  'Central American',
  'Salvadoran',
  'Amazonian',
  'Andean',
]

export const productionTagCategories = [
  {
    id: 'course',
    name: 'Course',
    color: 'blue',
    exclusive: false,
    minTags: 1,
    maxTags: 5,
    tags: ['appetizer', 'main', 'side', 'dessert', 'breakfast'],
  },
  {
    id: 'weather',
    name: 'Weather',
    color: 'amber',
    exclusive: true,
    minTags: 1,
    maxTags: 1,
    tags: ['cold', 'warm', 'any'],
  },
  {
    id: 'occasion',
    name: 'Occasion',
    color: 'purple',
    exclusive: true,
    minTags: 1,
    maxTags: 1,
    tags: ['Everyday', 'Weekend', 'Festive'],
  },
  {
    id: 'cuisine',
    name: 'Cuisine',
    color: 'emerald',
    exclusive: false,
    minTags: 1,
    maxTags: 5,
    tags: productionCuisines,
  },
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function seedProduction(db: any, _pool: Pool): Promise<void> {
  // 1. Seed global metadata configuration if missing
  const existingConfig = await db
    .select()
    .from(metadataConfigTable)
    .where(eq(metadataConfigTable.id, 'global'))

  if (existingConfig.length === 0) {
    console.log('[Seed:Production] Seeding global metadata configuration...')
    await db.insert(metadataConfigTable).values({
      id: 'global',
      mandatoryFields: {
        title: true,
        ingredients: true,
        instructions: true,
        image_url: false,
        description: false,
        yield_amount: false,
        prep_time_minutes: false,
        cook_time_minutes: false,
        source_url: false,
      },
      mandatoryCategories: ['course', 'weather', 'occasion', 'cuisine'],
      timeTrackingMode: 'prep_and_cook',
    })
  }

  // 2. Seed production tag categories if not present
  for (const cat of productionTagCategories) {
    const existing = await db
      .select()
      .from(tagCategories)
      .where(eq(tagCategories.id, cat.id))

    if (existing.length === 0) {
      await db.insert(tagCategories).values(cat)
    }
  }

  // 4. Seed default template if not present
  const existingTemplate = await db
    .select()
    .from(templates)
    .where(eq(templates.id, 'tpl_default'))

  if (existingTemplate.length === 0) {
    console.log('[Seed:Production] Seeding default template (tpl_default)...')
    await db.insert(templates).values({
      id: 'tpl_default',
      name: 'Classic Recipe',
      description:
        'Standard culinary recipe layout with culinary metrics, ingredients table, rich text method, and mobile-friendly card.',
      isDefault: true,
      currentVersionId: 1,
    })

    await db.insert(templateVersions).values({
      templateId: 'tpl_default',
      version: 1,
      changeSummary: 'Default system template',
      fieldsSchema: [
        {
          id: 'fld_title',
          name: 'Recipe Title',
          type: 'text',
          required: true,
          order: 1,
          config: { multiline: false, placeholder: 'e.g. Spaghetti Carbonara' },
        },
        {
          id: 'fld_description',
          name: 'Summary / Description',
          type: 'text',
          required: false,
          order: 2,
          config: { multiline: true, resizable: true, placeholder: 'Briefly describe this dish...' },
        },
        {
          id: 'fld_image',
          name: 'Cover Photo',
          type: 'image',
          required: false,
          order: 3,
          config: { placeholder: 'https://images.unsplash.com/...' },
        },
        {
          id: 'fld_yield',
          name: 'Yield / Portions',
          type: 'text',
          required: false,
          order: 4,
          config: { multiline: false, placeholder: 'e.g. 4 servings' },
        },
        {
          id: 'fld_prep_time',
          name: 'Prep Time',
          type: 'number',
          required: false,
          order: 5,
          config: { min: 0, step: 1, unit: 'min' },
        },
        {
          id: 'fld_cook_time',
          name: 'Cook Time',
          type: 'number',
          required: false,
          order: 6,
          config: { min: 0, step: 1, unit: 'min' },
        },
        {
          id: 'fld_total_time',
          name: 'Total Time',
          type: 'number',
          required: false,
          order: 7,
          config: { min: 0, step: 1, unit: 'min' },
        },
        {
          id: 'fld_tags',
          name: 'Tags & Taxonomy',
          type: 'tag_category',
          required: false,
          order: 8,
          config: {},
        },
        {
          id: 'fld_sep_content',
          name: 'Method & Ingredients',
          type: 'separator',
          required: false,
          order: 9,
          config: { separatorStyle: 'heading' },
        },
        {
          id: 'fld_ingredients',
          name: 'Ingredients Table',
          type: 'ingredient_table',
          required: true,
          order: 10,
          config: {},
        },
        {
          id: 'fld_instructions',
          name: 'Preparation Method',
          type: 'rich_text',
          required: true,
          order: 11,
          config: {},
        },
        {
          id: 'fld_notes',
          name: 'Cook Notes',
          type: 'text',
          required: false,
          order: 12,
          config: { multiline: true, resizable: true, placeholder: 'Storage instructions, pairing ideas...' },
        },
      ],
      cardLayout: {
        columns: 4,
        widgets: [
          { id: 'w_image', fieldId: 'fld_image', widgetType: 'image_banner', col: 1, row: 1, colSpan: 4, rowSpan: 2 },
          { id: 'w_title', fieldId: 'fld_title', widgetType: 'title_header', col: 1, row: 3, colSpan: 4, rowSpan: 1 },
          { id: 'w_prep', fieldId: 'fld_prep_time', widgetType: 'metric_chip', col: 1, row: 4, colSpan: 2, rowSpan: 1, options: { showLabel: true } },
          { id: 'w_cook', fieldId: 'fld_cook_time', widgetType: 'metric_chip', col: 3, row: 4, colSpan: 2, rowSpan: 1, options: { showLabel: true } },
          { id: 'w_tags', fieldId: 'fld_tags', widgetType: 'tag_chips', col: 1, row: 5, colSpan: 4, rowSpan: 1 },
        ],
      },
    })
  }
}
